jobs:
  - name: test-manifest
    type: manifest
    steps:
      - IN: test-img
  - name: test-job-1
    type: runSh
    steps:
      - IN: test-img
        switch: off
      - OUT: test-img
      - TASK:
        - script: "echo test-job-1"
  - name: test-job-2
    type: runSh
    steps:
      - IN: test-img
        switch: on
      - OUT: test-manifest
      - TASK:
        - script: "echo test-job-2"

resources:
  - name: test-img
    type: image
    integration: deepika-docker
    pointer:
      sourceName: "library/nginx"
    seed:
      versionName: latest
